nginx:
  restart: always
  build: .
  dockerfile: ./nginx/Dockerfile
  ports:
    - "5000:5000"
  links:
    - registry:registry

registry:
  image: registry:2
  restart: always
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
   - ./registry-data:/var/lib/registry
  ports:
    - "5000"
